### ISSUE TITLE
update via toolbox failed.

### ISSUE THREAD

**Issue by enrymodd** [Ansem-SoD/Picofly#8] opened 2023-05-20 04:54 UTC
by updating the firmware with the update.bin file, the same is recognized and flashed, but the old version always remains when restarted, by consulting the info section.

**Comment by gogo505** [comment] 2023-05-20 10:18
#5

**Comment by gogo505** [comment] 2023-05-20 10:19
#5 
Duplicate of #5

**Comment by Ansem-SoD** [comment] 2023-05-21 11:51
updated to 2.73 error codes are in changelog.md

**Closed by Ansem-SoD** 2023-05-21 11:51 UTC
